# Telegram Bot Configuration
bot-token: "6468385890:AAHtdGJsUniBR5EfJ-GczhouFiY_nVsvxGQ"
bot-username: "Bot"
# Показывать ли инструкцию при входе незарегистрированным игрокам
show-registration-instructions: false
# Ссылка на бота
bot-link: "https://t.me/shelldev_template_test_bot"
# Текст инструкции
registration-instructions: |
  &6=== Инструкция по регистрации ===
  &eДля игры на сервере необходимо привязать аккаунт к Telegram
  &e1. Перейдите в бот: {bot-link}
  &e2. Отправьте команду: /reg {player}
  &e3. После регистрации вы сможете войти на сервер
  &6==============================